### ISSUE TITLE
tidak menghubungkan halaman tambah.php ke functions.php pada halaman tambah.php

### ISSUE THREAD

**Issue by josua1111** [josuaokky/Kode_Program-Proyek2-#18]

**Comment by OkkyY** [comment]
disini saya tidak membuat fungsi untuk menghubungkan halaman tambah.php dengan functions.php, dimana pada file functions.php ada fungsi untuk menambahkan data dalam database di phpmysql
solusinya saya menambahkan fungsi require 'functions.php'.

**Comment by OkkyY** [comment]
![image](https://user-images.githubusercontent.com/57055622/68573165-bc119e00-0499-11ea-97f4-4e115c7a4061.png)
